services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - VITE_API_URL=http://backend:5001

  backend:
    build: ./backend
    networks:
      - app_network
    volumes:
      - ./backend/data:/app/data

networks:
  app_network:
    driver: bridge